name: Deploy Vite React to VPS

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
          source: "dist/*"
          target: "/var/www/html/petainaja/"
          strip_components: 1
          rm: true
      
      - name: Reload Apache
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
          script: |
            sudo systemctl reload apache2
            echo "✅ Deployment completed at $(date)"